### PR TITLE
Add support for a gauge function and metric to track the maximum number of devices permitted to connect to a Talaria instance.

### PR DESCRIPTION
**Pull request by ChaitanyaSingla**
We need to introduce a metric in Talaria that reflects the maximum number of devices permitted to connect to a Talaria instance. This pull request includes the addition of a gauge function and a metric to monitor the maximum allowed device connections for Talaria.

Reference issue for this MR: https://github.com/xmidt-org/talaria/issues/299

cc: @Sachin4403

### CODE REVIEW

**Review by Sachin4403 — APPROVED** [review]

**Review by johnabass — APPROVED** [review]

**Comment by johnabass** [comment]
@ChaitanyaSingla you need to sign the CLA agreement in order for this to proceed.

**Comment by denopink** [comment]
@ChaitanyaSingla you need to sign the CLA agreement in order for this to proceed.

as @johnabass pointed out

**Comment by ChaitanyaSingla** [comment]
@johnabass I have already signed the CLA agreement, but it is still showing as pending.

**Comment by ChaitanyaSingla** [comment]
@denopink Done.

**Comment by denopink** [comment]
looks like it worked this time, thanks again!

**Review by denopink — APPROVED** [review]
lgtm! 🍻

**Pull request merged**
